### ISSUE TITLE
Theme inspector is not showing up in developer tools

### ISSUE THREAD

**Issue by dooman87** [Shopify/shopify-theme-inspector#75]
### Problem

It was working fine until Chrome updated to version 86.

### More Information

I tried to reinstall the app, but that's didn't help. Chrome info:

Google Chrome | 86.0.4240.111 (Official Build) (x86_64)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | macOS Version 10.15.7 (Build 19H2)
JavaScript | V8 8.6.395.17
Flash | 32.0.0.445 /Users/dimka/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.445/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --enable-gpu-rasterization --enable-quic --flag-switches-end

**Comment by wizardlyhel** [comment]
Hmm.. I updated Chrome to Version 86.0.4240.111 (Official Build) (x86_64) on the same Mac OS version. I cannot reproduce what you are experiencing.

**Comment by dooman87** [comment]
Here is a video from my laptop - https://drive.google.com/file/d/16yWm14UN28jWCX6X7c96gsPqOr--AGSj/view?usp=sharing.

I couldn't figure out what is a pattern - sometimes it shows up and sometimes it's not...

**Comment by wizardlyhel** [comment]
Hi - Thanks for the video.

I can see there is a massive rewrite in `{{ content_for_header }}`. This is not recommended.

The Shopify Inspector tool relies on two JS variable (for now - maybe more in future):

* JS variables `Shopify` and `Shopify.shop` need to exist - So that the extension knows that it's on a Shopify store (show/hides the panel in devtool)
* JS variable `BOOMR.application=".*"` needs to exist - So that the extension knows which rendering engine did this html render resulted from

The reason why it's sometimes there and sometimes not there is because the Chrome extension sometimes can find the 2 required JS variable and sometimes not.

I find that the devtool panel becomes more consistent when you open the inspector tool after the page has fully loaded. If you navigate from a non Shopify page (or new tab/window) to a Shopify page, devtool will have a hard time to determine if this is a Shopify store. However, if you close the devtool and reopen it again, it will appear.
